### ISSUE TITLE
ssi_expander.py: "NameError: name 'file' is not defined" with python3

### ISSUE THREAD

**Issue by navadev** [danvk/ssi-server#9]
Error:
```
user@workstation user % python3 ../ssi-server/ssi_expander.py site site_expanded
Traceback (most recent call last):
  File "/Users/user/work/site/../ssi-server/ssi_expander.py", line 45, in <module>
    process(source, dest)
  File "/Users/user/work/site/../ssi-server/ssi_expander.py", line 27, in process
    file(dest_path, 'w').write(ssi.InlineIncludes(src_path, "/%s" % os.path.relpath(src_path)))

```

Here's what I found on the internet:
#
The file function was removed in Python 3. In Python 3, you should use the open function instead.

`open(dest_path, 'w').write(ssi.InlineIncludes(src_path, "/%s" % os.path.relpath(src_path)))`

This resolves the error.

**Comment by danvk** [comment]
I'd be happy to accept a PR that updates this to Python 3.
